server:
  port : 8081
spring:
  datasource:
    url: "jdbc:sqlserver://localhost;databaseName=blogapi"
    username: "admin"
    password: "jamaldin123+"
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      dialect: "org.hibernate.dialect.SQLServer2012Dialect"
      ddl-auto: update